import JSZip from 'jszip'
import type { Mosaic, FaceMask, LegoColor } from '../../types/index.js'
import { renderFaceMosaicPng } from './face-mosaic-png.js'
import { renderAssemblyGuidePng } from './assembly-guide-png.js'
import { generateBrickLinkXml } from './bricklink-xml.js'
import { generateStudioLdr } from './studio-ldr.js'

function buildReadme(omittedBL: string[], placeholderLDR: string[]): string {
  const blNote = omittedBL.length > 0
    ? `\n> Note: The following colours were omitted from bricklink-wanted.xml because their BrickLink colour IDs are not yet mapped: ${omittedBL.join(', ')}.\n`
    : ''
  const ldrNote = placeholderLDR.length > 0
    ? `\n> Note: The following colours use LDraw placeholder colour 16 in studio-model.ldr because their Studio colour IDs are not yet mapped: ${placeholderLDR.join(', ')}.\n`
    : ''

  return `# Faceplate Mosaic — Results

Generated by [Faceplate.me](https://faceplate.me) — turn any face into a LEGO mosaic.

All image processing occurred entirely in your browser. No image data was sent to any server to produce this download.

## Files

- **face-mosaic.png** — Your masked face mosaic as a transparent PNG (brick colours visible inside the face boundary; transparent outside). Use this for sharing or as a reference while building.
- **assembly-guide.png** — A printable build reference: each brick labelled with a colour letter, a positioning grid (thick yellow lines through the centre, thinner lines every 4 bricks) to help you count studs while assembling, and a legend mapping each letter to its colour name and brick count.
- **original-image.jpg** — Your original cropped photo for reference.
- **bricklink-wanted.xml** — A BrickLink Wanted List you can import at bricklink.com to order exactly the bricks you need.
- **studio-model.ldr** — An LDraw model file you can open in BrickLink Studio to visualise and share your mosaic digitally.
- **readme.md** — This file.
${blNote}${ldrNote}
## Learn More

Visit [Faceplate.me](https://faceplate.me) to create more mosaics.
`
}

export async function downloadResultsZip(
  mosaic: Mosaic,
  mask: FaceMask,
  palette: LegoColor[],
  originalImageBlob: Blob,
): Promise<void> {
  const zip = new JSZip()

  // face-mosaic.png
  try {
    const pngBlob = await renderFaceMosaicPng(mosaic, mask, palette)
    zip.file('face-mosaic.png', pngBlob)
  } catch {
    // continue without PNG
  }

  // assembly-guide.png
  try {
    const assemblyBlob = await renderAssemblyGuidePng(mosaic, mask, palette)
    zip.file('assembly-guide.png', assemblyBlob)
  } catch {
    // continue without assembly guide
  }

  // original-image.jpg
  zip.file('original-image.jpg', originalImageBlob)

  // bricklink-wanted.xml
  const { xml, omittedColours } = generateBrickLinkXml(mosaic, mask, palette)
  zip.file('bricklink-wanted.xml', xml)

  // studio-model.ldr
  const { ldr, placeholderColours } = generateStudioLdr(mosaic, mask, palette)
  zip.file('studio-model.ldr', ldr)

  // readme.md
  zip.file('readme.md', buildReadme(omittedColours, placeholderColours))

  const blob = await zip.generateAsync({ type: 'blob' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'faceplate-results.zip'
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
