import type { Mosaic, FaceMask, LegoColor } from '../../types/index.js'

const FALLBACK_COLOR = 16  // LDraw "current colour" placeholder

export function generateStudioLdr(
  mosaic: Mosaic,
  mask: FaceMask,
  palette: LegoColor[],
): { ldr: string; placeholderColours: string[] } {
  const paletteMap = new Map(palette.map(c => [c.id, c]))
  const lines: string[] = [
    '0 Faceplate Mosaic',
    '0 Generated by Faceplate.me',
  ]
  const placeholderSet = new Set<string>()

  for (let r = 0; r < mosaic.height; r++) {
    const row = mask.rows[r]
    for (let c = row.leftCol; c <= row.rightCol; c++) {
      const colorId = mosaic.grid[r][c]
      const color = paletteMap.get(colorId)
      const ldrColor = color?.studioColorId ?? FALLBACK_COLOR
      if (!color?.studioColorId) {
        placeholderSet.add(color?.name ?? String(colorId))
      }
      const x = c * 20
      const z = r * 20
      lines.push(`1 ${ldrColor} ${x} 0 ${z} 1 0 0 0 1 0 0 0 1 3024.dat`)
    }
  }

  return { ldr: lines.join('\n'), placeholderColours: [...placeholderSet] }
}
