import { describe, it, expect } from 'vitest'
import { generateStudioLdr } from '../../src/lib/export/studio-ldr.js'
import type { Mosaic, FaceMask, LegoColor } from '../../src/types/index.js'

const palette: LegoColor[] = [
  { id: 1, name: 'White', rgb: [255,255,255], studioColorId: 15 },
  { id: 2, name: 'Black', rgb: [0,0,0],       studioColorId: 0  },
  { id: 3, name: 'Red',   rgb: [255,0,0]       },  // no studioColorId
]

const fullMask: FaceMask = {
  rows: [
    { leftCol: 0, rightCol: 1 },
    { leftCol: 0, rightCol: 1 },
  ],
  mosaicWidth: 2,
}

const mosaic: Mosaic = {
  grid: [[1, 2], [1, 2]],
  width: 32, height: 2 as any,
  algorithmVersion: '1.0.0', pieceType: '1x1-plate', mask: null,
}

describe('generateStudioLdr', () => {
  it('single brick produces a correct LDraw line', () => {
    const singleMask: FaceMask = { rows: [{ leftCol: 0, rightCol: 0 }], mosaicWidth: 2 }
    const singleMosaic: Mosaic = { ...mosaic, height: 1 as any, grid: [[1]] }
    const { ldr } = generateStudioLdr(singleMosaic, singleMask, palette)
    // x=0, z=0, color=15
    expect(ldr).toContain('1 15 0 0 0 1 0 0 0 1 0 0 0 1 3024.dat')
  })

  it('masked cells are omitted from the LDR file', () => {
    const leftMask: FaceMask = { rows: [{ leftCol: 0, rightCol: 0 }, { leftCol: 0, rightCol: 0 }], mosaicWidth: 2 }
    const { ldr } = generateStudioLdr(mosaic, leftMask, palette)
    // Only col 0 visible → x=0 lines only; x=20 should not appear
    expect(ldr).not.toContain('1 0 20 ')
  })

  it('coordinate mapping: row 2 col 3 → x=60, z=40', () => {
    const bigMask: FaceMask = { rows: [
      { leftCol: 0, rightCol: 3 },
      { leftCol: 0, rightCol: 3 },
      { leftCol: 0, rightCol: 3 },
    ], mosaicWidth: 4 }
    const bigMosaic: Mosaic = { ...mosaic, height: 3 as any, grid: [[1,1,1,1],[1,1,1,1],[1,1,1,1]] }
    const { ldr } = generateStudioLdr(bigMosaic, bigMask, palette)
    // Row 2, col 3: x=60, z=40
    expect(ldr).toContain('60 0 40')
  })

  it('missing studioColorId falls back to colour 16', () => {
    const redMosaic: Mosaic = { ...mosaic, height: 1 as any, grid: [[3, 3]] }
    const singleRow: FaceMask = { rows: [{ leftCol: 0, rightCol: 1 }], mosaicWidth: 2 }
    const { ldr, placeholderColours } = generateStudioLdr(redMosaic, singleRow, palette)
    expect(ldr).toContain('1 16 ')
    expect(placeholderColours).toContain('Red')
  })

  it('includes LDraw header lines', () => {
    const { ldr } = generateStudioLdr(mosaic, fullMask, palette)
    expect(ldr).toContain('0 Faceplate Mosaic')
    expect(ldr).toContain('0 Generated by Faceplate.me')
  })
})
